version: '2'
networks:
  egghost:
    driver: bridge
volumes:                # 创建自定义卷
  node_modules:       # 卷名
  mongo_data:
services:
  vuenginx:
    build:
      context: ../vue-admin
      dockerfile: Dockerfile
    networks:
      - egghost
    ports:
      - '80:80'
    depends_on:
      - egg-server
  mongo:
    networks:
      - egghost
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /Users/apple/mongodb/data/db:/data/db   # mac本地开发环境
      # - /usr/local/src/data/db:/data/db     # 生产环境
  egg-server:
    networks:
      - egghost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7001:7001'
    depends_on:
      - mongo
    tty: true
    links:
      - mongo:mongo